config/routes.rb
Raghava::Application.routes.draw do
  #devise_for :user1s
  get "galleries/image"
  resources :orders

  resources :customers

  resources :contacts

  #resources :registrations

  #resources :logins

  root :to => 'contacts#index'

  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, :email, :cell, :address, presence: true
	validates :cell, numericality: { only_integer: true }
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders #@customer.orders
	
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :customer, :foreign_key => 'customer_id'
	#@order.customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.paginate(:page => params[:page], :per_page => 2)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        UserMailer.registration_confirmation(@contact).deliver
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :cell, :address)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @customer }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :email)
    end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def image
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_id, :pname, :price, :qty)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cell %><br>
    <%= f.text_field :cell %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Cell</th>
      <th>Address</th>
      <th></th>
            <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.cell %></td>
        <td><%= contact.address %></td>
        <td><%= link_to 'Show', contact %></td>
        
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>
<br />
<br />
<div class="flickr_pagination">
    <%= will_paginate @contacts, :container => false %>
  </div>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Cell:</strong>
  <%= @contact.cell %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>
<br />
<% @my = params[:id] %>
<%= @my %>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<table border="1">
<tr><td>Product Name</td><td>Price</td><td>Qty</td></tr>
<% @customer.orders.each do |c| %>
<tr>
<td><%= link_to c.pname, c %> </td><td><%= c.price %> </td><td><%= c.qty %> </td>
</tr>
<% end %>
</table>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/galleries/image.html.erb
<%= image_tag("tajmahal.jpeg", size: "430x240", alt: "Taj Mahal") %>
<%= video_tag("http://mirrorblender.top-ix.org/peach/bigbuckbunny_movies/big_buck_bunny_1080p_stereo.ogg", controls: true, autobuffer: true, height: '240', width: '430') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Planet</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<body>
<div id="templatemo_container">
	<div id="templatemo_banner">
    	<div id="logo"></div>
        <!--  Free CSS Templates @ www.TemplateMo.com  -->
        <div id="search_section">
            <form action="#" method="get">
                <input type="text" value="Enter keyword here..." name="q" size="10" id="searchfield" title="searchfield" onfocus="clearText(this)" onblur="clearText(this)" />
              <input type="submit" name="Search" value="Search" alt="Search" id="searchbutton" title="Search" />
            </form>
        </div> 

    </div> <!-- end of banner -->
    
    <div id="templatemo_menu">

      <%= render :partial => 'membership/menu' %>
           
	  </div> <!-- end of menu -->

	<div id="templatemo_content_wrapper">
    	<div id="templatemo_content">
    
    	<div class="column_w210 fl">
        
          <div class="header_01">
              Latest Blog Posts
            </div>
            
      <div class="latest_news">
            <div class="header_03">[29-OCT-2024]</div>
            <div class="header_02"><a href="#">Aenean a bibendum augue</a></div>
                
                <p>Praesent eu ligula quis nibh ullamcorper tempor non ultrices lacus.</p>
      </div>
                        
            <div class="margin_bottom_10"></div>
            
            <div class="latest_news">
                <div class="header_03">[28-OCT-2024]</div>
            <div class="header_02"><a href="#">Nulla pharetra leo eget </a></div>
                <p>Vivamus condimentum justo id tortor rhoncus eu ornare sem malesuada. </p>
			</div>
                        
            <div class="margin_bottom_10"></div>
            
            <div class="latest_news">
                <div class="header_03">[27-OCT-2024]</div>
    		    <div class="header_02"><a href="#">Vivamus metus justo</a></div>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
			</div>
                        
            <div class="margin_bottom_10"></div>
            
            <div class="rc_btn_01"><a href="#">Read All</a></div>
            
        
        	<div class="cleaner"></div>
        </div> <!-- end of a column -->
        
        <div class="column_w430 fl vl_divider">
        	
            <%= image_tag("templatemo_image_01.jpg", :alt => "image") %>
            
            <div class="header_01">Welcome to our photo site!</div>
            
            <%= yield %>
        
        	<div class="cleaner"></div>        
        </div> <!-- end of a column -->
        
       <div class="column_w210 fl vl_divider">
        
        	<div class="header_01">
            	Categories
            </div>
            
	        <%= render :partial => 'membership/right' %> 
            
        
        	<div class="cleaner"></div>
        </div> <!-- end of a column -->
        
        <div class="margin_bottom_20 h_divider"></div>        
        <div class="margin_bottom_20"></div>
        
        <div class="column_w920">
        
          <%= render :partial => 'membership/bottomimages'  %>
        </div>
    
    	<div class="cleaner"></div>
	</div> <!-- end of wrapper 02 -->        
    </div> <!-- end of wrapper 01 -->
    
    <div id="templatemo_footer">
    
    <ul class="footer_list">
            <li><a href="#" class="current">Home</a></li>
            <li><a href="#">Gallery</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Forum</a></li>
            <li><a href="#">About Us</a></li>
            <li class="last"><a href="#">Contact Us</a></li>
        </ul> 
        
        <div class="margin_bottom_10"></div>
        
        Copyright © 2048 <a href="#">Company Name</a> | <a href="http://www.iwebsitetemplate.com" target="_parent">Website Templates</a> by <a href="http://www.templatemo.com" target="_parent">Free Templates</a>
        
        <div class="margin_bottom_10"></div>
        
        <a href="http://validator.w3.org/check?uri=referer"><img style="border:0;width:88px;height:31px" src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Transitional" width="88" height="31" vspace="8" border="0" /></a>
                <a href="http://jigsaw.w3.org/css-validator/check/referer"><img style="border:0;width:88px;height:31px"  src="http://jigsaw.w3.org/css-validator/images/vcss-blue" alt="Valid CSS!" vspace="8" border="0" /></a>
                
   	</div> <!-- end of footer -->
</div> <!-- end of container -->
<!--  Free CSS Template is provided by www.TemplateMo.com  -->
<div align=center>This template  downloaded form <a href='http://all-free-download.com/free-website-templates/'>free website templates</a></div>

</body>
</html>

app/views/layouts/brain.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Raghava</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div id="topPan">
	<a><%= image_tag("logo.gif", :width => "219", :height => "58", :border => "0", :alt => "Brain Tech", :title => "Brain Tech") %></a>
	
    <div id="topimagePan"><%= image_tag("blank.gif", :alt => "image") %></div> 
	<ul>
		<li class="home">home</li>
		<li><a href="#">about us</a></li>
		<li><a href="#">support</a></li>
		<li><a href="#">solutions</a></li>
		<li><a href="#">books</a></li>
		<li><a href="#">contact</a></li>
  </ul>
</div>

<div id="bodyPan">
  <div id="leftPan">
  	<%= yield %>
  </div>
  <div id="rightPan">
  	<form action="" method="post" class="form1">
		<h2>member login</h2>
		<label>Name:</label>
		<input name="" type="text" />
		<label>Passward:</label>
		<input name="" type="password" />
		<label class="label1">a resistered member?</label>
		<input name="GO" type="submit" class="botton" id="GO" value="GO" />
	</form>
	<h3>more links</h3>
	<ul>
		<li><a href="#">www.braintech.com</a></li>
		<li><a href="#">www.brainmod.com</a></li>
		<li><a href="#">www.braintech2.com</a></li>
		<li><a href="#">www.modedu.com</a></li>
		<li><a href="#">www.modtech3.com</a></li>
		<li><a href="#">www.university.com</a></li>
	</ul>
	<div id="rightform2Pan">
	<form action="" method="get" class="form2">
		<h2>search</h2>
		<label>www.</label>
		<input name="" type="text" />
		<select name="select">
		  <option>.com</option>
		  <option>.org</option>
	    </select>
		<input name="search" type="submit"  class="search" id="search" value="SEARCH"/>
	</form>
	</div>
  </div>
</div>
<div id="bodyBottomPan">
  <div id="BottomLeftPan">
  	<p>about our <span>university</span></p>
  </div>
  
  <div id="BottomMiddlePan">
  	<p>Sed eros tellus, blandit in, tempus a, imperdiet at, ante. Phasellugittiss pedeamet,. Mauris mauris nibh, euismod nec, sagittis imperdietgittise, nonummy at, dui. Integer semimp sapien, faucibus it amet, tristique eu, blandit sit amet, massa. Nam lacinia.Proin ut velit id maurisluctus urisr vestibulum. Aenean condimentum.Donec iaculis </p>
	<p class="more"><a href="#">more</a></p>
  </div>
</div>
<div id="footerPan">
	<ul>
		<li><a href="#">home </a>| </li>
		<li><a href="#">about us</a>| </li>
		<li><a href="#">support</a>| </li>
		<li><a href="#">solutions</a>| </li>
		<li><a href="#">books</a>| </li>
		<li><a href="#">contact</a></li>
		</ul>
		<p class="copyright">©braintech. all right reserved.</p>
		<div id="footerPanhtml"><a href="http://validator.w3.org/check?uri=referer" target="_blank">HTML</a></div>
    	<div id="footerPancss"><a href="http://jigsaw.w3.org/css-validator/check/referer" target="_blank">CSS</a></div>
		<ul class="templateworld">
  			<li>design by:</li>
			<li><a href="http://www.templateworld.com" target="_blank">Template World</a></li>
 	   </ul>
</div>
</body>
</html>

app/views/membership/_bottomimages.html.erb
         <div class="column_w190 fl margin_right_40">
            	<a href="#"><%= image_tag("templatemo_image_02.jpg", :alt => "image") %></a>
              <p>Nam sit amet justo vel libero tincidunt dignissim. Cras magna velit, pellentesque mattis, faucibus vitae, feugiat vitae. <a href="#">Read more...</a></p>                
          </div>
            
          <div class="column_w190 fl margin_right_40">
            	<a href="#"><%= image_tag("templatemo_image_03.jpg", :alt => "image") %></a>
          <p>Pellentesque tortor metus, gravida ut aliquet non, iaculis nec nisi. Null am ornare, mauris vitae vehicula veh icula. <a href="#">Read more...</a></p>                
          </div>
            
          <div class="column_w190 fl margin_right_40">
            	<a href="#"><%= image_tag("templatemo_image_04.jpg", :alt => "image") %></a>
          <p>Proin consequat interdum mauris id auctor. In justo dolor, luctus sed tristique vel, porttitor eu enim. In molestie vehicula pretium  iaculis. <a href="#">Read more...</a></p>                
          </div>
            
          <div class="column_w190 fl">
            	<a href="#"><%= image_tag("templatemo_image_05.jpg", :alt => "image") %></a>
          <p>Suspendisse odio erat, mattis in hend rerit id, iaculis at metus. Aliquam ligula justo, gravida sed pretium eu. <a href="#">Read more...</a></p>                
          </div>
        
       	  <div class="margin_bottom_15"></div>

app/views/membership/_brainyeild.html.erb
<h3>latest <span>blogs</span></h3>
		<h4><span>1.</span>kavin johnes</h4>
		<p><span>Lorem ipsum dolor sit amet, consectetuer</span> adipiscing elit. Cras sit amet neque a mauris semper sagittis. Sed facilisis turpis in elit. Nunc purus augue, ornare sed, bibendum vie</p>
		
	    <div id="leftblockoneLinkPan">
			<ul>
				<li class="comments">comments</li>
				<li class="more"><a href="#">more</a></li>
			</ul>
		</div>
		<p class="border"><%= image_tag("blank.gif", :alt => "image") %></p>
		<h4><span>2.</span>henry richard</h4>
		<p><span>Lorem ipsum dolor sit amet, consectetuer</span> adipiscing elit. Cras sit amet neque a mauris semper sagittis. Sed facilisis turpis in elit. Nunc purus augue, ornare sed, bibendum vie</p>
		<div id="leftblockoneLinktwoPan">
			<ul>
				<li class="comments">comments</li>
				<li class="more"><a href="#">more</a></li>
			</ul>
</div>

app/views/membership/_menu.html.erb
<ul>
    <li><a href="/" class="current"><span></span>Home</a></li>
    <li><a href="#"><span></span>Admin</a></li>
    <li><a href="/galleries/image"><span></span>Gallery</a></li>
    <li><a href="#"><span></span>Shop</a></li>            
   <li><a href="#"><span></span>Login</a></li> 
    <li><a href="/contacts/new"><span></span>Contact Us</a></li>
</ul>

app/views/membership/_right.html.erb
<ul class="category_list">
           		<li><a href="#">Lorem ipsum dolor</a></li>
                <li><a href="#">Aenean ac lobortis felis</a></li>
                <li><a href="#">Cras eros dolor</a></li>
                <li><a href="#">Vivamus orci velit</a></li>
                <li><a href="#">Proin ultrices eros</a></li>
                <li><a href="#">Aliquam ac nisl eget</a></li>
                <li><a href="#">Praesent vehicula tellus</a></li>
                <li><a href="#">Mauris egestas nunc</a></li>
                <li><a href="#">Ut semper porta magna</a></li>
                <li><a href="#">Donec ante risus</a></li>
                <li><a href="#">Nunc bibendum neque</a></li>
    		</ul>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.text_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :pname %><br>
    <%= f.text_field :pname %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :qty %><br>
    <%= f.text_field :qty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Pname</th>
      <th>Price</th>
      <th>Qty</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.customer_id %></td>
        <td><%= order.pname %></td>
        <td><%= order.price %></td>
        <td><%= order.qty %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer_id %>
</p>

<p>
  <strong>Pname:</strong>
  <%= @order.pname %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @order.qty %>
</p>
<table><tr>
	<td><%= @order.customer.name %></td><td><%= @order.customer.email %></td>
</tr>
</table>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>